---
- name: "{{ php_current_version }} - Install"
  homebrew:
    name: "shivammathur/php/php@{{ php_current_version }}"
    state: "{{ homebrew_package_state }}"

- name: "{{ php_current_version }} - brew unlink"
  shell: "brew unlink php@{{ php_current_version }}"
  register: php_brew_unlink_result
  changed_when: "'0 symlinks removed' not in php_brew_unlink_result.stdout"

- name: "{{ php_current_version }} - Register FPM port"
  set_fact:
    php_fpm_port: "{{ '90' + php_current_version|replace('.', '') }}"

- name: "{{ php_current_version }} - Get PHP path"
  shell: "brew --prefix shivammathur/php/php@{{ php_current_version }}"
  register: brew_prefix_php
  changed_when: False

- name: "{{ php_current_version }} - Register extensions for current version"
  set_fact:
    php_current_version_extensions: "php_{{ php_current_version|replace('.', '') }}_extensions"

- name: "{{ php_current_version }} - Install extension"
  homebrew:
    name: "shivammathur/extensions/{{ item }}@{{ php_current_version }}"
    state: "{{ homebrew_package_state }}"
  with_items: "{{ lookup('vars', php_current_version_extensions, default=php_extensions) }}"

- name: "{{ php_current_version }} - Set FPM config"
  template:
    src: php-fpm.conf.j2
    dest: "{{ brew_prefix }}/etc/php/{{ php_current_version }}/php-fpm.conf"
  notify: Restart PHP-FPM

- name: "{{ php_current_version }} - Delete old FPM config"
  file:
    dest: "{{ brew_prefix }}/etc/php/{{ php_current_version }}/php-fpm.d/www.conf"
    state: absent
  notify: Restart PHP-FPM

- name: "{{ php_current_version }} - Delete old custom config file"
  file:
    dest: "{{ php_custom_config_file }}"
    state: absent
  notify: Restart PHP-FPM

- name: "{{ php_current_version }} - Add custom config file"
  ini_file:
    dest: "{{ php_custom_config_file }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  when: item.when|default(true)
  with_items: "{{ php_custom_config }}"
  notify: Restart PHP-FPM

- name: Set .load_php for default version
  template:
    src: load_php.j2
    dest: "~/.load_php"
    mode: 0755
  when: php_current_version == php_default_version
